/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Submission {
    id: bigint;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export type Time = bigint;
export type ContentCategory =
    | { __kind__: "Post" }
    | { __kind__: "Blog" }
    | { __kind__: "News" }
    | { __kind__: "Article" };
export interface ContentItem {
    id: bigint;
    title: string;
    body: string;
    category: ContentCategory;
    imageUrl: Option<string>;
    author: string;
    createdAt: Time;
    published: boolean;
}
export type UserRole =
    | { __kind__: "admin" }
    | { __kind__: "user" }
    | { __kind__: "guest" };
export interface backendInterface {
    getAllSubmissions(): Promise<Array<Submission>>;
    getAllSubmissionsSortedByTimestamp(): Promise<Array<Submission>>;
    getSubmissionsByEmail(email: string): Promise<Array<Submission>>;
    getSubmissionsByPhone(phone: string): Promise<Array<Submission>>;
    submitContactForm(name: string, phone: string, email: string, message: string): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    isCallerAdmin(): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createContent(title: string, body: string, category: ContentCategory, imageUrl: Option<string>, author: string): Promise<bigint>;
    updateContent(id: bigint, title: string, body: string, category: ContentCategory, imageUrl: Option<string>, author: string, published: boolean): Promise<boolean>;
    deleteContent(id: bigint): Promise<boolean>;
    getAllPublishedContent(): Promise<Array<ContentItem>>;
    getPublishedContentByCategory(category: ContentCategory): Promise<Array<ContentItem>>;
    getAllContentAdmin(): Promise<Array<ContentItem>>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllSubmissions(): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return result;
        }
    }
    async getAllSubmissionsSortedByTimestamp(): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissionsSortedByTimestamp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissionsSortedByTimestamp();
            return result;
        }
    }
    async getSubmissionsByEmail(arg0: string): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionsByEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionsByEmail(arg0);
            return result;
        }
    }
    async getSubmissionsByPhone(arg0: string): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionsByPhone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionsByPhone(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async _initializeAccessControlWithSecret(userSecret: string): Promise<void> {
        return await (this.actor as any)._initializeAccessControlWithSecret(userSecret);
    }
    async getCallerUserRole(): Promise<UserRole> {
        return await (this.actor as any).getCallerUserRole();
    }
    async isCallerAdmin(): Promise<boolean> {
        return await (this.actor as any).isCallerAdmin();
    }
    async assignCallerUserRole(user: Principal, role: UserRole): Promise<void> {
        return await (this.actor as any).assignCallerUserRole(user, role);
    }
    async createContent(title: string, body: string, category: ContentCategory, imageUrl: Option<string>, author: string): Promise<bigint> {
        const candidImageUrl = imageUrl.__kind__ === "Some" ? [imageUrl.value] : [];
        return await (this.actor as any).createContent(title, body, this._encodeCat(category), candidImageUrl, author);
    }
    async updateContent(id: bigint, title: string, body: string, category: ContentCategory, imageUrl: Option<string>, author: string, published: boolean): Promise<boolean> {
        const candidImageUrl = imageUrl.__kind__ === "Some" ? [imageUrl.value] : [];
        return await (this.actor as any).updateContent(id, title, body, this._encodeCat(category), candidImageUrl, author, published);
    }
    async deleteContent(id: bigint): Promise<boolean> {
        return await (this.actor as any).deleteContent(id);
    }
    async getAllPublishedContent(): Promise<Array<ContentItem>> {
        const result = await (this.actor as any).getAllPublishedContent();
        return result.map((item: any) => this._decodeContentItem(item));
    }
    async getPublishedContentByCategory(category: ContentCategory): Promise<Array<ContentItem>> {
        const result = await (this.actor as any).getPublishedContentByCategory(this._encodeCat(category));
        return result.map((item: any) => this._decodeContentItem(item));
    }
    async getAllContentAdmin(): Promise<Array<ContentItem>> {
        const result = await (this.actor as any).getAllContentAdmin();
        return result.map((item: any) => this._decodeContentItem(item));
    }
    private _encodeCat(cat: ContentCategory): any {
        return { [cat.__kind__]: null };
    }
    private _decodeContentItem(item: any): ContentItem {
        const catKey = Object.keys(item.category)[0] as "Post" | "Blog" | "News" | "Article";
        const imageUrl: Option<string> = item.imageUrl && item.imageUrl.length > 0
            ? { __kind__: "Some", value: item.imageUrl[0] }
            : { __kind__: "None" };
        return {
            id: item.id,
            title: item.title,
            body: item.body,
            category: { __kind__: catKey },
            imageUrl,
            author: item.author,
            createdAt: item.createdAt,
            published: item.published,
        };
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
